name: "refresh"

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install depend
        run: |
          sudo apt update
          sudo apt install dpkg-dev bzip2 xz-utils zstd -y

      - name: 自动读取插件描述生成分类索引
        run: |
          cd ./debs
          rm -f Packages
          touch Packages
          find . -maxdepth 1 -name "*.deb" | while read file
          do
            info=$(dpkg -I "$file" control)
            desc=$(echo "$info" | grep Description:)
            section="工具插件"
            if echo "$desc" | grep -q "键盘";then
              section="键盘增强"
            elif echo "$desc" | grep -E -q "系统|状态栏|锁屏|通知|手势|后台|动画|音量|电量|桌面|壁纸|音频|媒体|充电|弹窗|屏幕";then
              section="系统增强"
            elif echo "$desc" | grep -E -q "账号|切换|下载|文件|管理器|注入|屏蔽|广告|脚本|Safari|翻译|投屏|画中画|限制解除";then
              section="功能拓展"
            fi
            echo "$info" | sed '/Section:/d' > temp.txt
            echo "Section: $section" >> temp.txt
            cat temp.txt >> Packages
            echo "" >> Packages
          done
          rm -f temp.txt
          gzip -k -f Packages
          bzip2 -k -f Packages
          xz -k -f Packages
          zstd -k -f Packages

      - name: upload file
        uses: actions/upload-artifact@v4
        with:
          path: ./debs
          name: repo-file

      - name: deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./debs
