name: "refresh"

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed


jobs:
  build:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:


      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0



      - name: install depend
        run: |
          sudo apt update
          sudo apt install dpkg-dev bzip2 xz-utils zstd -y



      - name: Check deb Section
        run: |

          for deb in ./debs/*.deb; do

            if [ -f "$deb" ]; then

              echo "===================="

              echo "$deb"

              dpkg-deb -f "$deb" Package

              dpkg-deb -f "$deb" Version

              dpkg-deb -f "$deb" Architecture

              dpkg-deb -f "$deb" Section

              echo "===================="

            fi

          done




      - name: Refresh Packages
        run: |

          rm -f Packages
          rm -f Packages.bz2
          rm -f Packages.xz
          rm -f Packages.zst


          dpkg-scanpackages -m ./debs /dev/null > Packages



          bzip2 -9k Packages


          xz -9k --extreme Packages


          zstd --ultra -22 -k Packages -o Packages.zst




      - name: Debug Packages
        run: |

          echo "===== Packages Preview ====="

          head -80 Packages




      - name: save change if local change
        run: |

          git config --global user.email "action@github.com"

          git config --global user.name "GitHub Action"


          git add .


          if ! git diff --staged --exit-code 1>/dev/null; then

            git commit -m "Refresh Packages"

            git push

          else

            echo "No changes"

          fi




      - name: download remove_all_actions
        run: |

          sudo curl -L \
          -o /usr/bin/remove_all_actions \
          https://raw.githubusercontent.com/invalidunit/action/main/remove_all_actions


          sudo chmod 0755 /usr/bin/remove_all_actions




      - name: remove all old actions
        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          GH_REPO: ${{ github.repository }}

        run: |

          remove_all_actions
